version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    command: npm run start:dev
  frontend:
    build: ./frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
    command: npm run start